# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('ingredient_type', models.CharField(max_length=100)),
                ('ingredient_owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_date', models.DateField()),
                ('salad_time', models.CharField(max_length=100)),
                ('salad_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salads.Salad'),
        ),
    ]
